### ISSUE TITLE
Why the magMeas is the sum up of inertial frame mag and body frame mag

### ISSUE THREAD

**Issue by xeonqq** [priseborough/InertialNav#21]
Hello, Paul
I am very inteseted in your work and had a little doubt here.

As shown in the matlab code, here you have
```
%% derive equations for fusion of magnetic field measurement
magMeas = transpose(Tbn)*[magN;magE;magD] + [magX;magY;magZ]; % predicted measurement
```
I think the magnetometer sensor only measures  [magX;magY;magZ], which is earth mag field in body frame.
so I think
```
magMeas = transpose(Tbn)*[magN;magE;magD]
```
for the observation function would be correct

and then 
```
innovation = magMeas - [magX;magY;magZ]
```
Could you explain a little about this?

**Comment by rafaelmendy** [comment]
Hi
I think the magnetometer measures all magnetic fields around itself and not only magnetic field of earth.
So, this formulation has supposed that there may be a specific kind of magnetic field in body frame. for example magnetic field of brushless motors or servos. magnetometer measures them as well. 
So it's the correct and in my thought talent job to let the algorithm compensate and self calibrate these kind of magnetic fields.

**Comment by xeonqq** [comment]
@rafaelmendy Thank you very much, I think what you said makes sense, it finally clear my doubt on this. But just another thing pop up on my mind, if EKF can estimate the mag noise/offset, why Ardupilot would still need manual mag calibration. Maybe to provide a better initial guess of the value?

**Comment by rafaelmendy** [comment]
Yes
I think so.
