### ISSUE TITLE
calc_truth_deriv

### ISSUE THREAD

**Issue by RyanWangCode** [priseborough/InertialNav#25]
What's the meaning of line 46 in the calc_truth_deriv.m？
`acc_deriv = 10*w*sin(wt) - 10*Acc - 10*Vel;` 
 Is this a formula like F=m*acc+c*vel+k*pos？But why it is 10？@priseborough
Thanks.

**Comment by priseborough** [comment]
It's harmonic vibration, and 10 is the amplitude

**Comment by RyanWangCode** [comment]
OK，thanks.
